// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID          uuid.UUID
	OwnerUserID uuid.NullUUID
}

type User struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Tags      []string
	Metadata  json.RawMessage
}
